// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULE278J9wsfKf9o1cd-rXbqJ2A2OQVRg',
    appId: '1:179434683012:web:31513a1e35d1494f4ae0d1',
    messagingSenderId: '179434683012',
    projectId: 'suraksha-setu-9808d',
    authDomain: 'suraksha-setu-9808d.firebaseapp.com',
    storageBucket: 'suraksha-setu-9808d.firebasestorage.app',
    measurementId: 'G-CHMBD8VFJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClmS_RlvHRCdeEEJcFcQ3B8gm3dJDAyK8',
    appId: '1:179434683012:android:5dfa0a0aa291b4f04ae0d1',
    messagingSenderId: '179434683012',
    projectId: 'suraksha-setu-9808d',
    storageBucket: 'suraksha-setu-9808d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwqdPScdOjKCmG1N_oD8rel7ek5wBN6S0',
    appId: '1:179434683012:ios:82ee6fbd6f45603f4ae0d1',
    messagingSenderId: '179434683012',
    projectId: 'suraksha-setu-9808d',
    storageBucket: 'suraksha-setu-9808d.firebasestorage.app',
    androidClientId: '179434683012-ha1tte90nl26qboiuip478n6q0ted49l.apps.googleusercontent.com',
    iosClientId: '179434683012-b8j1r8t72riucj4pdammr2cpaa2mipml.apps.googleusercontent.com',
    iosBundleId: 'com.example.policeDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwqdPScdOjKCmG1N_oD8rel7ek5wBN6S0',
    appId: '1:179434683012:ios:82ee6fbd6f45603f4ae0d1',
    messagingSenderId: '179434683012',
    projectId: 'suraksha-setu-9808d',
    storageBucket: 'suraksha-setu-9808d.firebasestorage.app',
    androidClientId: '179434683012-ha1tte90nl26qboiuip478n6q0ted49l.apps.googleusercontent.com',
    iosClientId: '179434683012-b8j1r8t72riucj4pdammr2cpaa2mipml.apps.googleusercontent.com',
    iosBundleId: 'com.example.policeDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDULE278J9wsfKf9o1cd-rXbqJ2A2OQVRg',
    appId: '1:179434683012:web:3603ddd04b669d244ae0d1',
    messagingSenderId: '179434683012',
    projectId: 'suraksha-setu-9808d',
    authDomain: 'suraksha-setu-9808d.firebaseapp.com',
    storageBucket: 'suraksha-setu-9808d.firebasestorage.app',
    measurementId: 'G-T01F3ST1N5',
  );
}
